// small_tree_base: base class to handle reduced tree ntuples
// File generated with generate_small_tree_base.exe

#ifndef H_SMALL_TREE_BASE
#define H_SMALL_TREE_BASE

#include <vector>
#include <string>

#include "TTree.h"
#include "TChain.h"

class small_tree_base{
public:
  small_tree_base(); // Constructor to create tree
  small_tree_base(const std::string &filename); // Constructor to read tree

  int Add(const std::string &filename);
  long GetEntries() const;
  virtual void GetEntry(const long entry);

  virtual void Fill();
  void Write();

  virtual std::string Type() const;

  static const double bad_val_;

  virtual ~small_tree_base();

  float const & dphi_wlep() const;
  float & dphi_wlep();
  float const & ht() const;
  float & ht();
  float const & met() const;
  float & met();
  float const & met_phi() const;
  float & met_phi();
  float const & min_mt_bmet() const;
  float & min_mt_bmet();
  float const & min_mt_bmet_with_w_mass() const;
  float & min_mt_bmet_with_w_mass();
  float const & mindphin_metjet() const;
  float & mindphin_metjet();
  float const & mt() const;
  float & mt();
  float const & ntrupv_mean() const;
  float & ntrupv_mean();
  float const & weight() const;
  float & weight();
  int const & event() const;
  int & event();
  int const & lumiblock() const;
  int & lumiblock();
  int const & nbl() const;
  int & nbl();
  int const & nbm() const;
  int & nbm();
  int const & nbt() const;
  int & nbt();
  int const & nels() const;
  int & nels();
  int const & njets() const;
  int & njets();
  int const & nleps() const;
  int & nleps();
  int const & nmus() const;
  int & nmus();
  int const & npv() const;
  int & npv();
  int const & ntrupv() const;
  int & ntrupv();
  int const & nvels() const;
  int & nvels();
  int const & nvmus() const;
  int & nvmus();
  int const & run() const;
  int & run();
  std::vector<bool> const & els_ispf() const;
  std::vector<bool> & els_ispf();
  std::vector<bool> const & els_sigid() const;
  std::vector<bool> & els_sigid();
  std::vector<bool> const & els_tru_tm() const;
  std::vector<bool> & els_tru_tm();
  std::vector<bool> const & mus_sigid() const;
  std::vector<bool> & mus_sigid();
  std::vector<bool> const & mus_tru_tm() const;
  std::vector<bool> & mus_tru_tm();
  std::vector<bool> const & tks_from_tau() const;
  std::vector<bool> & tks_from_tau();
  std::vector<bool> const & tks_from_tauhad() const;
  std::vector<bool> & tks_from_tauhad();
  std::vector<bool> const & tks_from_taulep() const;
  std::vector<bool> & tks_from_taulep();
  std::vector<bool> const & tks_from_w() const;
  std::vector<bool> & tks_from_w();
  std::vector<float> const & els_eta() const;
  std::vector<float> & els_eta();
  std::vector<float> const & els_miniso_10_ch() const;
  std::vector<float> & els_miniso_10_ch();
  std::vector<float> const & els_miniso_tr10() const;
  std::vector<float> & els_miniso_tr10();
  std::vector<float> const & els_miniso_tr10_pfpu() const;
  std::vector<float> & els_miniso_tr10_pfpu();
  std::vector<float> const & els_mt() const;
  std::vector<float> & els_mt();
  std::vector<float> const & els_phi() const;
  std::vector<float> & els_phi();
  std::vector<float> const & els_pt() const;
  std::vector<float> & els_pt();
  std::vector<float> const & els_reliso() const;
  std::vector<float> & els_reliso();
  std::vector<float> const & els_reliso_r01() const;
  std::vector<float> & els_reliso_r01();
  std::vector<float> const & els_reliso_r015() const;
  std::vector<float> & els_reliso_r015();
  std::vector<float> const & els_reliso_r02() const;
  std::vector<float> & els_reliso_r02();
  std::vector<float> const & els_reliso_r03() const;
  std::vector<float> & els_reliso_r03();
  std::vector<float> const & els_reliso_r04() const;
  std::vector<float> & els_reliso_r04();
  std::vector<float> const & els_tru_dr() const;
  std::vector<float> & els_tru_dr();
  std::vector<float> const & jets_csv() const;
  std::vector<float> & jets_csv();
  std::vector<float> const & jets_eta() const;
  std::vector<float> & jets_eta();
  std::vector<float> const & jets_id() const;
  std::vector<float> & jets_id();
  std::vector<float> const & jets_phi() const;
  std::vector<float> & jets_phi();
  std::vector<float> const & jets_pt() const;
  std::vector<float> & jets_pt();
  std::vector<float> const & mus_eta() const;
  std::vector<float> & mus_eta();
  std::vector<float> const & mus_miniso_10_ch() const;
  std::vector<float> & mus_miniso_10_ch();
  std::vector<float> const & mus_miniso_tr10() const;
  std::vector<float> & mus_miniso_tr10();
  std::vector<float> const & mus_miniso_tr10_pfpu() const;
  std::vector<float> & mus_miniso_tr10_pfpu();
  std::vector<float> const & mus_mt() const;
  std::vector<float> & mus_mt();
  std::vector<float> const & mus_phi() const;
  std::vector<float> & mus_phi();
  std::vector<float> const & mus_pt() const;
  std::vector<float> & mus_pt();
  std::vector<float> const & mus_reliso() const;
  std::vector<float> & mus_reliso();
  std::vector<float> const & mus_reliso_r01() const;
  std::vector<float> & mus_reliso_r01();
  std::vector<float> const & mus_reliso_r015() const;
  std::vector<float> & mus_reliso_r015();
  std::vector<float> const & mus_reliso_r02() const;
  std::vector<float> & mus_reliso_r02();
  std::vector<float> const & mus_reliso_r03() const;
  std::vector<float> & mus_reliso_r03();
  std::vector<float> const & mus_reliso_r04() const;
  std::vector<float> & mus_reliso_r04();
  std::vector<float> const & mus_tru_dr() const;
  std::vector<float> & mus_tru_dr();
  std::vector<float> const & tks_eta() const;
  std::vector<float> & tks_eta();
  std::vector<float> const & tks_mt() const;
  std::vector<float> & tks_mt();
  std::vector<float> const & tks_phi() const;
  std::vector<float> & tks_phi();
  std::vector<float> const & tks_pt() const;
  std::vector<float> & tks_pt();
  std::vector<float> const & tks_r03_ch() const;
  std::vector<float> & tks_r03_ch();
  std::vector<float> const & tks_tru_dp() const;
  std::vector<float> & tks_tru_dp();
  std::vector<float> const & tks_tru_dr() const;
  std::vector<float> & tks_tru_dr();
  std::vector<int> const & els_charge() const;
  std::vector<int> & els_charge();
  std::vector<int> const & els_tru_id() const;
  std::vector<int> & els_tru_id();
  std::vector<int> const & els_tru_momid() const;
  std::vector<int> & els_tru_momid();
  std::vector<int> const & mus_charge() const;
  std::vector<int> & mus_charge();
  std::vector<int> const & mus_tru_id() const;
  std::vector<int> & mus_tru_id();
  std::vector<int> const & mus_tru_momid() const;
  std::vector<int> & mus_tru_momid();
  std::vector<int> const & tks_from_pv() const;
  std::vector<int> & tks_from_pv();
  std::vector<int> const & tks_id() const;
  std::vector<int> & tks_id();
  std::vector<int> const & tks_num_prongs() const;
  std::vector<int> & tks_num_prongs();
  std::vector<int> const & tks_tru_id() const;
  std::vector<int> & tks_tru_id();
  unsigned const & mc_type() const;
  unsigned & mc_type();

  __attribute__((noreturn)) virtual float const & dphi_wlep_reliso() const;
  __attribute__((noreturn)) virtual float & dphi_wlep_reliso();
  __attribute__((noreturn)) virtual float const & ht30() const;
  __attribute__((noreturn)) virtual float & ht30();
  __attribute__((noreturn)) virtual float const & lep_pt() const;
  __attribute__((noreturn)) virtual float & lep_pt();
  __attribute__((noreturn)) virtual float const & lep_pt_reliso() const;
  __attribute__((noreturn)) virtual float & lep_pt_reliso();
  __attribute__((noreturn)) virtual float const & mht() const;
  __attribute__((noreturn)) virtual float & mht();
  __attribute__((noreturn)) virtual float const & mht30() const;
  __attribute__((noreturn)) virtual float & mht30();
  __attribute__((noreturn)) virtual float const & mj() const;
  __attribute__((noreturn)) virtual float & mj();
  __attribute__((noreturn)) virtual float const & mj_10() const;
  __attribute__((noreturn)) virtual float & mj_10();
  __attribute__((noreturn)) virtual float const & mj_20() const;
  __attribute__((noreturn)) virtual float & mj_20();
  __attribute__((noreturn)) virtual float const & mj_30() const;
  __attribute__((noreturn)) virtual float & mj_30();
  __attribute__((noreturn)) virtual float const & mj_40() const;
  __attribute__((noreturn)) virtual float & mj_40();
  __attribute__((noreturn)) virtual float const & mj_cands() const;
  __attribute__((noreturn)) virtual float & mj_cands();
  __attribute__((noreturn)) virtual float const & mj_cands_trim() const;
  __attribute__((noreturn)) virtual float & mj_cands_trim();
  __attribute__((noreturn)) virtual float const & mj_eta25() const;
  __attribute__((noreturn)) virtual float & mj_eta25();
  __attribute__((noreturn)) virtual float const & mj_nolep_30() const;
  __attribute__((noreturn)) virtual float & mj_nolep_30();
  __attribute__((noreturn)) virtual float const & mj_r08() const;
  __attribute__((noreturn)) virtual float & mj_r08();
  __attribute__((noreturn)) virtual float const & mj_r10() const;
  __attribute__((noreturn)) virtual float & mj_r10();
  __attribute__((noreturn)) virtual float const & mj_r14() const;
  __attribute__((noreturn)) virtual float & mj_r14();
  __attribute__((noreturn)) virtual float const & mj_siglep_30() const;
  __attribute__((noreturn)) virtual float & mj_siglep_30();
  __attribute__((noreturn)) virtual float const & mt_reliso() const;
  __attribute__((noreturn)) virtual float & mt_reliso();
  __attribute__((noreturn)) virtual float const & st() const;
  __attribute__((noreturn)) virtual float & st();
  __attribute__((noreturn)) virtual float const & st_reliso() const;
  __attribute__((noreturn)) virtual float & st_reliso();
  __attribute__((noreturn)) virtual int const & nbl30() const;
  __attribute__((noreturn)) virtual int & nbl30();
  __attribute__((noreturn)) virtual int const & nbm30() const;
  __attribute__((noreturn)) virtual int & nbm30();
  __attribute__((noreturn)) virtual int const & nbt30() const;
  __attribute__((noreturn)) virtual int & nbt30();
  __attribute__((noreturn)) virtual int const & nels_reliso() const;
  __attribute__((noreturn)) virtual int & nels_reliso();
  __attribute__((noreturn)) virtual int const & nfjets() const;
  __attribute__((noreturn)) virtual int & nfjets();
  __attribute__((noreturn)) virtual int const & nfjets_10() const;
  __attribute__((noreturn)) virtual int & nfjets_10();
  __attribute__((noreturn)) virtual int const & nfjets_20() const;
  __attribute__((noreturn)) virtual int & nfjets_20();
  __attribute__((noreturn)) virtual int const & nfjets_30() const;
  __attribute__((noreturn)) virtual int & nfjets_30();
  __attribute__((noreturn)) virtual int const & nfjets_40() const;
  __attribute__((noreturn)) virtual int & nfjets_40();
  __attribute__((noreturn)) virtual int const & nfjets_cands() const;
  __attribute__((noreturn)) virtual int & nfjets_cands();
  __attribute__((noreturn)) virtual int const & nfjets_cands_trim() const;
  __attribute__((noreturn)) virtual int & nfjets_cands_trim();
  __attribute__((noreturn)) virtual int const & nfjets_eta25() const;
  __attribute__((noreturn)) virtual int & nfjets_eta25();
  __attribute__((noreturn)) virtual int const & nfjets_nolep_30() const;
  __attribute__((noreturn)) virtual int & nfjets_nolep_30();
  __attribute__((noreturn)) virtual int const & nfjets_r08() const;
  __attribute__((noreturn)) virtual int & nfjets_r08();
  __attribute__((noreturn)) virtual int const & nfjets_r10() const;
  __attribute__((noreturn)) virtual int & nfjets_r10();
  __attribute__((noreturn)) virtual int const & nfjets_r14() const;
  __attribute__((noreturn)) virtual int & nfjets_r14();
  __attribute__((noreturn)) virtual int const & nfjets_siglep_30() const;
  __attribute__((noreturn)) virtual int & nfjets_siglep_30();
  __attribute__((noreturn)) virtual int const & nisotk10() const;
  __attribute__((noreturn)) virtual int & nisotk10();
  __attribute__((noreturn)) virtual int const & nisotk10_mt100() const;
  __attribute__((noreturn)) virtual int & nisotk10_mt100();
  __attribute__((noreturn)) virtual int const & nisotk15() const;
  __attribute__((noreturn)) virtual int & nisotk15();
  __attribute__((noreturn)) virtual int const & nisotk15_mt100() const;
  __attribute__((noreturn)) virtual int & nisotk15_mt100();
  __attribute__((noreturn)) virtual int const & nisotks() const;
  __attribute__((noreturn)) virtual int & nisotks();
  __attribute__((noreturn)) virtual int const & njets30() const;
  __attribute__((noreturn)) virtual int & njets30();
  __attribute__((noreturn)) virtual int const & nleps_reliso() const;
  __attribute__((noreturn)) virtual int & nleps_reliso();
  __attribute__((noreturn)) virtual int const & nmc_els() const;
  __attribute__((noreturn)) virtual int & nmc_els();
  __attribute__((noreturn)) virtual int const & nmc_htaus() const;
  __attribute__((noreturn)) virtual int & nmc_htaus();
  __attribute__((noreturn)) virtual int const & nmc_ltaus() const;
  __attribute__((noreturn)) virtual int & nmc_ltaus();
  __attribute__((noreturn)) virtual int const & nmc_mus() const;
  __attribute__((noreturn)) virtual int & nmc_mus();
  __attribute__((noreturn)) virtual int const & nmus_reliso() const;
  __attribute__((noreturn)) virtual int & nmus_reliso();
  __attribute__((noreturn)) virtual int const & ntaus() const;
  __attribute__((noreturn)) virtual int & ntaus();
  __attribute__((noreturn)) virtual int const & ntaus_againstEMu() const;
  __attribute__((noreturn)) virtual int & ntaus_againstEMu();
  __attribute__((noreturn)) virtual int const & ntaus_againstEMu_mt100() const;
  __attribute__((noreturn)) virtual int & ntaus_againstEMu_mt100();
  __attribute__((noreturn)) virtual int const & ntaus_mt100() const;
  __attribute__((noreturn)) virtual int & ntaus_mt100();
  __attribute__((noreturn)) virtual int const & nvels10() const;
  __attribute__((noreturn)) virtual int & nvels10();
  __attribute__((noreturn)) virtual int const & nvels_reliso() const;
  __attribute__((noreturn)) virtual int & nvels_reliso();
  __attribute__((noreturn)) virtual int const & nvmus10() const;
  __attribute__((noreturn)) virtual int & nvmus10();
  __attribute__((noreturn)) virtual int const & nvmus_reliso() const;
  __attribute__((noreturn)) virtual int & nvmus_reliso();
  __attribute__((noreturn)) virtual std::vector<bool> const & jets_bhad() const;
  __attribute__((noreturn)) virtual std::vector<bool> & jets_bhad();
  __attribute__((noreturn)) virtual std::vector<bool> const & jets_bhad_tru() const;
  __attribute__((noreturn)) virtual std::vector<bool> & jets_bhad_tru();
  __attribute__((noreturn)) virtual std::vector<bool> const & jets_blep() const;
  __attribute__((noreturn)) virtual std::vector<bool> & jets_blep();
  __attribute__((noreturn)) virtual std::vector<bool> const & jets_blep_tru() const;
  __attribute__((noreturn)) virtual std::vector<bool> & jets_blep_tru();
  __attribute__((noreturn)) virtual std::vector<bool> const & mc_els_id() const;
  __attribute__((noreturn)) virtual std::vector<bool> & mc_els_id();
  __attribute__((noreturn)) virtual std::vector<bool> const & mc_els_reco() const;
  __attribute__((noreturn)) virtual std::vector<bool> & mc_els_reco();
  __attribute__((noreturn)) virtual std::vector<bool> const & mc_mus_id() const;
  __attribute__((noreturn)) virtual std::vector<bool> & mc_mus_id();
  __attribute__((noreturn)) virtual std::vector<bool> const & mc_mus_reco() const;
  __attribute__((noreturn)) virtual std::vector<bool> & mc_mus_reco();
  __attribute__((noreturn)) virtual std::vector<bool> const & taus_againstEMu() const;
  __attribute__((noreturn)) virtual std::vector<bool> & taus_againstEMu();
  __attribute__((noreturn)) virtual std::vector<float> const & els_d0() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_d0();
  __attribute__((noreturn)) virtual std::vector<float> const & els_dz() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_dz();
  __attribute__((noreturn)) virtual std::vector<float> const & els_mindr_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_mindr_0();
  __attribute__((noreturn)) virtual std::vector<float> const & els_mindr_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_mindr_25();
  __attribute__((noreturn)) virtual std::vector<float> const & els_mindr_rem_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_mindr_rem_0();
  __attribute__((noreturn)) virtual std::vector<float> const & els_mindr_rem_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_mindr_rem_25();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_10() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_10();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_10_pfpu() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_10_pfpu();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_15() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_15();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_tr07() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_tr07();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_tr07_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_tr07_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & els_miniso_tr10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_miniso_tr10_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & els_ptrel_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_ptrel_0();
  __attribute__((noreturn)) virtual std::vector<float> const & els_ptrel_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_ptrel_25();
  __attribute__((noreturn)) virtual std::vector<float> const & els_ptrel_rem_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_ptrel_rem_0();
  __attribute__((noreturn)) virtual std::vector<float> const & els_ptrel_rem_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & els_ptrel_rem_25();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_10_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_10_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_10_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_10_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_10_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_10_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_10_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_10_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_20_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_20_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_20_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_20_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_20_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_20_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_20_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_20_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_30_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_30_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_30_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_30_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_30_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_30_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_30_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_30_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_40_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_40_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_40_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_40_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_40_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_40_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_40_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_40_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_trim_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_trim_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_trim_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_trim_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_trim_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_trim_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_cands_trim_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_cands_trim_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_eta25_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_eta25_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_eta25_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_eta25_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_eta25_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_eta25_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_eta25_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_eta25_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_nconst() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_nconst();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_nolep_30_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_nolep_30_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_nolep_30_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_nolep_30_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_nolep_30_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_nolep_30_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_nolep_30_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_nolep_30_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r08_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r08_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r08_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r08_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r08_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r08_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r08_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r08_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r10_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r10_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r10_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r10_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r10_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r10_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r10_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r10_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r14_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r14_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r14_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r14_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r14_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r14_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_r14_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_r14_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_siglep_30_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_siglep_30_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_siglep_30_m() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_siglep_30_m();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_siglep_30_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_siglep_30_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & fjets_siglep_30_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & fjets_siglep_30_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & isotk_dzpv() const;
  __attribute__((noreturn)) virtual std::vector<float> & isotk_dzpv();
  __attribute__((noreturn)) virtual std::vector<float> const & isotk_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & isotk_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & isotk_iso() const;
  __attribute__((noreturn)) virtual std::vector<float> & isotk_iso();
  __attribute__((noreturn)) virtual std::vector<float> const & isotk_mt() const;
  __attribute__((noreturn)) virtual std::vector<float> & isotk_mt();
  __attribute__((noreturn)) virtual std::vector<float> const & isotk_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & isotk_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & jets_dphi_lep() const;
  __attribute__((noreturn)) virtual std::vector<float> & jets_dphi_lep();
  __attribute__((noreturn)) virtual std::vector<float> const & jets_dphi_met() const;
  __attribute__((noreturn)) virtual std::vector<float> & jets_dphi_met();
  __attribute__((noreturn)) virtual std::vector<float> const & jets_dphi_sum() const;
  __attribute__((noreturn)) virtual std::vector<float> & jets_dphi_sum();
  __attribute__((noreturn)) virtual std::vector<float> const & jets_islep() const;
  __attribute__((noreturn)) virtual std::vector<float> & jets_islep();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_els_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_els_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_els_mpdr() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_els_mpdr();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_els_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_els_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_htaus_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_htaus_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_htaus_mpdr() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_htaus_mpdr();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_htaus_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_htaus_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_ltaus_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_ltaus_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_ltaus_mpdr() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_ltaus_mpdr();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_ltaus_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_ltaus_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_mus_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_mus_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_mus_mpdr() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_mus_mpdr();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_mus_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_mus_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & mc_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & mc_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_d0() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_d0();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_dz() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_dz();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_mindr_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_mindr_0();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_mindr_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_mindr_25();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_mindr_rem_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_mindr_rem_0();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_mindr_rem_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_mindr_rem_25();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_10() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_10();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_10_pfpu() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_10_pfpu();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_15() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_15();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_tr07() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_tr07();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_tr07_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_tr07_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_miniso_tr10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_miniso_tr10_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_ptrel_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_ptrel_0();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_ptrel_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_ptrel_25();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_ptrel_rem_0() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_ptrel_rem_0();
  __attribute__((noreturn)) virtual std::vector<float> const & mus_ptrel_rem_25() const;
  __attribute__((noreturn)) virtual std::vector<float> & mus_ptrel_rem_25();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_CombinedIsolationDeltaBetaCorrRaw3Hits() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_CombinedIsolationDeltaBetaCorrRaw3Hits();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_chargedIsoPtSum() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_chargedIsoPtSum();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_eta() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_eta();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_mt() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_mt();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_phi() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_phi();
  __attribute__((noreturn)) virtual std::vector<float> const & taus_pt() const;
  __attribute__((noreturn)) virtual std::vector<float> & taus_pt();
  __attribute__((noreturn)) virtual std::vector<float> const & tks_mini_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & tks_mini_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & tks_mini_ne() const;
  __attribute__((noreturn)) virtual std::vector<float> & tks_mini_ne();
  __attribute__((noreturn)) virtual std::vector<float> const & tks_r02_ch() const;
  __attribute__((noreturn)) virtual std::vector<float> & tks_r02_ch();
  __attribute__((noreturn)) virtual std::vector<float> const & tks_r02_ne() const;
  __attribute__((noreturn)) virtual std::vector<float> & tks_r02_ne();
  __attribute__((noreturn)) virtual std::vector<float> const & tks_r03_ne() const;
  __attribute__((noreturn)) virtual std::vector<float> & tks_r03_ne();
  __attribute__((noreturn)) virtual std::vector<int> const & mc_id() const;
  __attribute__((noreturn)) virtual std::vector<int> & mc_id();
  __attribute__((noreturn)) virtual std::vector<int> const & taus_decayMode() const;
  __attribute__((noreturn)) virtual std::vector<int> & taus_decayMode();
  __attribute__((noreturn)) virtual std::vector<int> const & taus_n_pfcands() const;
  __attribute__((noreturn)) virtual std::vector<int> & taus_n_pfcands();
  __attribute__((noreturn)) virtual std::vector<size_t> const & mc_mom() const;
  __attribute__((noreturn)) virtual std::vector<size_t> & mc_mom();

protected:
  TChain chain_;
  TTree tree_;
  long entry_;
  const bool read_only_;

private:
  class VectorLoader{
  public:
    VectorLoader();
  private:
    static bool loaded_;
  };

  static VectorLoader vl_;
  float dphi_wlep_;
  TBranch *b_dphi_wlep_;
  mutable bool c_dphi_wlep_;
  float ht_;
  TBranch *b_ht_;
  mutable bool c_ht_;
  float met_;
  TBranch *b_met_;
  mutable bool c_met_;
  float met_phi_;
  TBranch *b_met_phi_;
  mutable bool c_met_phi_;
  float min_mt_bmet_;
  TBranch *b_min_mt_bmet_;
  mutable bool c_min_mt_bmet_;
  float min_mt_bmet_with_w_mass_;
  TBranch *b_min_mt_bmet_with_w_mass_;
  mutable bool c_min_mt_bmet_with_w_mass_;
  float mindphin_metjet_;
  TBranch *b_mindphin_metjet_;
  mutable bool c_mindphin_metjet_;
  float mt_;
  TBranch *b_mt_;
  mutable bool c_mt_;
  float ntrupv_mean_;
  TBranch *b_ntrupv_mean_;
  mutable bool c_ntrupv_mean_;
  float weight_;
  TBranch *b_weight_;
  mutable bool c_weight_;
  int event_;
  TBranch *b_event_;
  mutable bool c_event_;
  int lumiblock_;
  TBranch *b_lumiblock_;
  mutable bool c_lumiblock_;
  int nbl_;
  TBranch *b_nbl_;
  mutable bool c_nbl_;
  int nbm_;
  TBranch *b_nbm_;
  mutable bool c_nbm_;
  int nbt_;
  TBranch *b_nbt_;
  mutable bool c_nbt_;
  int nels_;
  TBranch *b_nels_;
  mutable bool c_nels_;
  int njets_;
  TBranch *b_njets_;
  mutable bool c_njets_;
  int nleps_;
  TBranch *b_nleps_;
  mutable bool c_nleps_;
  int nmus_;
  TBranch *b_nmus_;
  mutable bool c_nmus_;
  int npv_;
  TBranch *b_npv_;
  mutable bool c_npv_;
  int ntrupv_;
  TBranch *b_ntrupv_;
  mutable bool c_ntrupv_;
  int nvels_;
  TBranch *b_nvels_;
  mutable bool c_nvels_;
  int nvmus_;
  TBranch *b_nvmus_;
  mutable bool c_nvmus_;
  int run_;
  TBranch *b_run_;
  mutable bool c_run_;
  std::vector<bool> els_ispf_;
  std::vector<bool> *p_els_ispf_;
  TBranch *b_els_ispf_;
  mutable bool c_els_ispf_;
  std::vector<bool> els_sigid_;
  std::vector<bool> *p_els_sigid_;
  TBranch *b_els_sigid_;
  mutable bool c_els_sigid_;
  std::vector<bool> els_tru_tm_;
  std::vector<bool> *p_els_tru_tm_;
  TBranch *b_els_tru_tm_;
  mutable bool c_els_tru_tm_;
  std::vector<bool> mus_sigid_;
  std::vector<bool> *p_mus_sigid_;
  TBranch *b_mus_sigid_;
  mutable bool c_mus_sigid_;
  std::vector<bool> mus_tru_tm_;
  std::vector<bool> *p_mus_tru_tm_;
  TBranch *b_mus_tru_tm_;
  mutable bool c_mus_tru_tm_;
  std::vector<bool> tks_from_tau_;
  std::vector<bool> *p_tks_from_tau_;
  TBranch *b_tks_from_tau_;
  mutable bool c_tks_from_tau_;
  std::vector<bool> tks_from_tauhad_;
  std::vector<bool> *p_tks_from_tauhad_;
  TBranch *b_tks_from_tauhad_;
  mutable bool c_tks_from_tauhad_;
  std::vector<bool> tks_from_taulep_;
  std::vector<bool> *p_tks_from_taulep_;
  TBranch *b_tks_from_taulep_;
  mutable bool c_tks_from_taulep_;
  std::vector<bool> tks_from_w_;
  std::vector<bool> *p_tks_from_w_;
  TBranch *b_tks_from_w_;
  mutable bool c_tks_from_w_;
  std::vector<float> els_eta_;
  std::vector<float> *p_els_eta_;
  TBranch *b_els_eta_;
  mutable bool c_els_eta_;
  std::vector<float> els_miniso_10_ch_;
  std::vector<float> *p_els_miniso_10_ch_;
  TBranch *b_els_miniso_10_ch_;
  mutable bool c_els_miniso_10_ch_;
  std::vector<float> els_miniso_tr10_;
  std::vector<float> *p_els_miniso_tr10_;
  TBranch *b_els_miniso_tr10_;
  mutable bool c_els_miniso_tr10_;
  std::vector<float> els_miniso_tr10_pfpu_;
  std::vector<float> *p_els_miniso_tr10_pfpu_;
  TBranch *b_els_miniso_tr10_pfpu_;
  mutable bool c_els_miniso_tr10_pfpu_;
  std::vector<float> els_mt_;
  std::vector<float> *p_els_mt_;
  TBranch *b_els_mt_;
  mutable bool c_els_mt_;
  std::vector<float> els_phi_;
  std::vector<float> *p_els_phi_;
  TBranch *b_els_phi_;
  mutable bool c_els_phi_;
  std::vector<float> els_pt_;
  std::vector<float> *p_els_pt_;
  TBranch *b_els_pt_;
  mutable bool c_els_pt_;
  std::vector<float> els_reliso_;
  std::vector<float> *p_els_reliso_;
  TBranch *b_els_reliso_;
  mutable bool c_els_reliso_;
  std::vector<float> els_reliso_r01_;
  std::vector<float> *p_els_reliso_r01_;
  TBranch *b_els_reliso_r01_;
  mutable bool c_els_reliso_r01_;
  std::vector<float> els_reliso_r015_;
  std::vector<float> *p_els_reliso_r015_;
  TBranch *b_els_reliso_r015_;
  mutable bool c_els_reliso_r015_;
  std::vector<float> els_reliso_r02_;
  std::vector<float> *p_els_reliso_r02_;
  TBranch *b_els_reliso_r02_;
  mutable bool c_els_reliso_r02_;
  std::vector<float> els_reliso_r03_;
  std::vector<float> *p_els_reliso_r03_;
  TBranch *b_els_reliso_r03_;
  mutable bool c_els_reliso_r03_;
  std::vector<float> els_reliso_r04_;
  std::vector<float> *p_els_reliso_r04_;
  TBranch *b_els_reliso_r04_;
  mutable bool c_els_reliso_r04_;
  std::vector<float> els_tru_dr_;
  std::vector<float> *p_els_tru_dr_;
  TBranch *b_els_tru_dr_;
  mutable bool c_els_tru_dr_;
  std::vector<float> jets_csv_;
  std::vector<float> *p_jets_csv_;
  TBranch *b_jets_csv_;
  mutable bool c_jets_csv_;
  std::vector<float> jets_eta_;
  std::vector<float> *p_jets_eta_;
  TBranch *b_jets_eta_;
  mutable bool c_jets_eta_;
  std::vector<float> jets_id_;
  std::vector<float> *p_jets_id_;
  TBranch *b_jets_id_;
  mutable bool c_jets_id_;
  std::vector<float> jets_phi_;
  std::vector<float> *p_jets_phi_;
  TBranch *b_jets_phi_;
  mutable bool c_jets_phi_;
  std::vector<float> jets_pt_;
  std::vector<float> *p_jets_pt_;
  TBranch *b_jets_pt_;
  mutable bool c_jets_pt_;
  std::vector<float> mus_eta_;
  std::vector<float> *p_mus_eta_;
  TBranch *b_mus_eta_;
  mutable bool c_mus_eta_;
  std::vector<float> mus_miniso_10_ch_;
  std::vector<float> *p_mus_miniso_10_ch_;
  TBranch *b_mus_miniso_10_ch_;
  mutable bool c_mus_miniso_10_ch_;
  std::vector<float> mus_miniso_tr10_;
  std::vector<float> *p_mus_miniso_tr10_;
  TBranch *b_mus_miniso_tr10_;
  mutable bool c_mus_miniso_tr10_;
  std::vector<float> mus_miniso_tr10_pfpu_;
  std::vector<float> *p_mus_miniso_tr10_pfpu_;
  TBranch *b_mus_miniso_tr10_pfpu_;
  mutable bool c_mus_miniso_tr10_pfpu_;
  std::vector<float> mus_mt_;
  std::vector<float> *p_mus_mt_;
  TBranch *b_mus_mt_;
  mutable bool c_mus_mt_;
  std::vector<float> mus_phi_;
  std::vector<float> *p_mus_phi_;
  TBranch *b_mus_phi_;
  mutable bool c_mus_phi_;
  std::vector<float> mus_pt_;
  std::vector<float> *p_mus_pt_;
  TBranch *b_mus_pt_;
  mutable bool c_mus_pt_;
  std::vector<float> mus_reliso_;
  std::vector<float> *p_mus_reliso_;
  TBranch *b_mus_reliso_;
  mutable bool c_mus_reliso_;
  std::vector<float> mus_reliso_r01_;
  std::vector<float> *p_mus_reliso_r01_;
  TBranch *b_mus_reliso_r01_;
  mutable bool c_mus_reliso_r01_;
  std::vector<float> mus_reliso_r015_;
  std::vector<float> *p_mus_reliso_r015_;
  TBranch *b_mus_reliso_r015_;
  mutable bool c_mus_reliso_r015_;
  std::vector<float> mus_reliso_r02_;
  std::vector<float> *p_mus_reliso_r02_;
  TBranch *b_mus_reliso_r02_;
  mutable bool c_mus_reliso_r02_;
  std::vector<float> mus_reliso_r03_;
  std::vector<float> *p_mus_reliso_r03_;
  TBranch *b_mus_reliso_r03_;
  mutable bool c_mus_reliso_r03_;
  std::vector<float> mus_reliso_r04_;
  std::vector<float> *p_mus_reliso_r04_;
  TBranch *b_mus_reliso_r04_;
  mutable bool c_mus_reliso_r04_;
  std::vector<float> mus_tru_dr_;
  std::vector<float> *p_mus_tru_dr_;
  TBranch *b_mus_tru_dr_;
  mutable bool c_mus_tru_dr_;
  std::vector<float> tks_eta_;
  std::vector<float> *p_tks_eta_;
  TBranch *b_tks_eta_;
  mutable bool c_tks_eta_;
  std::vector<float> tks_mt_;
  std::vector<float> *p_tks_mt_;
  TBranch *b_tks_mt_;
  mutable bool c_tks_mt_;
  std::vector<float> tks_phi_;
  std::vector<float> *p_tks_phi_;
  TBranch *b_tks_phi_;
  mutable bool c_tks_phi_;
  std::vector<float> tks_pt_;
  std::vector<float> *p_tks_pt_;
  TBranch *b_tks_pt_;
  mutable bool c_tks_pt_;
  std::vector<float> tks_r03_ch_;
  std::vector<float> *p_tks_r03_ch_;
  TBranch *b_tks_r03_ch_;
  mutable bool c_tks_r03_ch_;
  std::vector<float> tks_tru_dp_;
  std::vector<float> *p_tks_tru_dp_;
  TBranch *b_tks_tru_dp_;
  mutable bool c_tks_tru_dp_;
  std::vector<float> tks_tru_dr_;
  std::vector<float> *p_tks_tru_dr_;
  TBranch *b_tks_tru_dr_;
  mutable bool c_tks_tru_dr_;
  std::vector<int> els_charge_;
  std::vector<int> *p_els_charge_;
  TBranch *b_els_charge_;
  mutable bool c_els_charge_;
  std::vector<int> els_tru_id_;
  std::vector<int> *p_els_tru_id_;
  TBranch *b_els_tru_id_;
  mutable bool c_els_tru_id_;
  std::vector<int> els_tru_momid_;
  std::vector<int> *p_els_tru_momid_;
  TBranch *b_els_tru_momid_;
  mutable bool c_els_tru_momid_;
  std::vector<int> mus_charge_;
  std::vector<int> *p_mus_charge_;
  TBranch *b_mus_charge_;
  mutable bool c_mus_charge_;
  std::vector<int> mus_tru_id_;
  std::vector<int> *p_mus_tru_id_;
  TBranch *b_mus_tru_id_;
  mutable bool c_mus_tru_id_;
  std::vector<int> mus_tru_momid_;
  std::vector<int> *p_mus_tru_momid_;
  TBranch *b_mus_tru_momid_;
  mutable bool c_mus_tru_momid_;
  std::vector<int> tks_from_pv_;
  std::vector<int> *p_tks_from_pv_;
  TBranch *b_tks_from_pv_;
  mutable bool c_tks_from_pv_;
  std::vector<int> tks_id_;
  std::vector<int> *p_tks_id_;
  TBranch *b_tks_id_;
  mutable bool c_tks_id_;
  std::vector<int> tks_num_prongs_;
  std::vector<int> *p_tks_num_prongs_;
  TBranch *b_tks_num_prongs_;
  mutable bool c_tks_num_prongs_;
  std::vector<int> tks_tru_id_;
  std::vector<int> *p_tks_tru_id_;
  TBranch *b_tks_tru_id_;
  mutable bool c_tks_tru_id_;
  unsigned mc_type_;
  TBranch *b_mc_type_;
  mutable bool c_mc_type_;
};

small_tree_base* NewTree(const std::type_info &type);

#include "small_tree_quick.hpp"

#endif
